% Name: Zheng Wen
% USC ID: 7112807212
% USC Email: zwen1423@usc.edu
% Submission Date 3/3/2020

function delete_if_1 = Unconditional_ST(cond_ST)
[m,n] = size(cond_ST);
delete_if_1 = zeros(m,n);
cond_ST_padd = reflectionPad(cond_ST, 1);
for i=1:m
    for j=1:n
        if cond_ST_padd(i + 1,j + 1) == 0
            continue
        else
            % spur
            ST11 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST12 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            % Single 4-connection
            ST21 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST22 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            % L Cluster
            ST31 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST32 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST33 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST34 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST41 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST42 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST43 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST44 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1);
            % 4-connected Offset
            ST51 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST52 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST53 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST54 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            % Spur corner Cluster
            ST61 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1 - 1,j + 1) || cond_ST_padd(i + 1,j + 1 + 1));
            ST62 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1, j + 1 - 1) || cond_ST_padd(i + 1 - 1,j + 1));
            ST63 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1,j + 1 - 1) || cond_ST_padd(i + 1 + 1,j + 1));
            ST64 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1,j + 1 - 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1, j + 1 + 1) || cond_ST_padd(i + 1 + 1,j + 1));
            % Corner Cluster
            ST71 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ...
                 cond_ST_padd(i + 1,j + 1 - 1);
            % Tee Branch
            ST81 = cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST82 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1);
            ST83 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1);
            ST84 = ~cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST91 = cond_ST_padd(i + 1 - 1,j + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            ST92 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1);
            ST93 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1);
            ST94 = cond_ST_padd(i + 1 - 1,j + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);
            % Vee Branch
            STA1 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1 + 1,j + 1 - 1) || cond_ST_padd(i + 1 + 1,j + 1) || cond_ST_padd(i + 1 + 1,j + 1 + 1));
            STA2 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && ...
                 (cond_ST_padd(i + 1 - 1,j + 1 + 1) || cond_ST_padd(i + 1,j + 1 + 1) || cond_ST_padd(i + 1 + 1,j + 1 + 1));
            STA3 = cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1 - 1,j + 1 - 1) || cond_ST_padd(i + 1 - 1,j + 1) || cond_ST_padd(i + 1 - 1,j + 1 + 1));
            STA4 = cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 + 1) && ...
                 (cond_ST_padd(i + 1 - 1,j + 1 - 1) || cond_ST_padd(i + 1, j + 1 - 1) || cond_ST_padd(i + 1 + 1,j + 1 - 1));
            % Diagonal Branch
            STB1 = cond_ST_padd(i + 1 - 1,j + 1) && ~cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1 - 1) && ~cond_ST_padd(i + 1 + 1,j + 1);
            STB2 = ~cond_ST_padd(i + 1 - 1,j + 1 - 1) && cond_ST_padd(i + 1 - 1,j + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1) && cond_ST_padd(i + 1 + 1,j + 1 + 1);
            STB3 = ~cond_ST_padd(i + 1 - 1,j + 1) && cond_ST_padd(i + 1 - 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1, j + 1 - 1) && ~cond_ST_padd(i + 1,j + 1 + 1) && ...
                 ~cond_ST_padd(i + 1 + 1,j + 1 - 1) && cond_ST_padd(i + 1 + 1,j + 1);
            STB4 = cond_ST_padd(i + 1 - 1,j + 1 - 1) && ~cond_ST_padd(i + 1 - 1,j + 1) && ...
                 ~cond_ST_padd(i + 1, j + 1 - 1) && cond_ST_padd(i + 1,j + 1 + 1) && ...
                 cond_ST_padd(i + 1 + 1,j + 1) && ~cond_ST_padd(i + 1 + 1,j + 1 + 1);

            delete_if_1(i,j) = ~(ST11 || ST12 || ST21 || ST22 || ST31 || ST32 || ST33 || ST34 || ST41 || ST42 || ST43 || ST44 || ...
                ST51 || ST52 || ST53 || ST54 || ST61 || ST62 || ST63 || ST64 || ST71 || ST81 || ST82 || ST83 || ST84 || ST91 || ST92 || ...
                ST93 || ST94 || STA1 || STA2 || STA3 || STA4 || STB1 || STB2 || STB3 || STB4);
        end
    end
end

end