% Name: Zheng Wen
% USC ID: 7112807212
% USC Email: zwen1423@usc.edu
% Submission Date 3/3/2020

function delete_if_1 = Unconditional_K(cond_K)
[m,n] = size(cond_K);
delete_if_1 = zeros(m,n);
cond_K_padd = reflectionPad(cond_K, 1);
for i=1:m
    for j=1:n
        if cond_K_padd(i + 1,j + 1) == 0
            continue
        end
        % spur
        ST11 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST12 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST13 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST14 = cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        % Single 4-connection
        ST21 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST22 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST23 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST24 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        % L Corner
        ST31 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST32 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST33 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST34 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        % Corner Cluster
        ST41 = cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1) && ...
             cond_K_padd(i + 1,j + 1 - 1);
        ST42 = cond_K_padd(i + 1,j + 1 + 1) && ...
            cond_K_padd(i + 1 + 1,j + 1) && cond_K_padd(i + 1 + 1,j + 1 + 1);
        % Tee Branch
        ST51 = cond_K_padd(i + 1 - 1,j + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1);
        ST52 = cond_K_padd(i + 1 - 1,j + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ...
             cond_K_padd(i + 1 + 1,j + 1);
        ST53 = cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1);
        ST54 = cond_K_padd(i + 1 - 1,j + 1) && ...
             cond_K_padd(i + 1, j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1);
        % Vee Branch
        ST61 = cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             (cond_K_padd(i + 1 + 1,j + 1 - 1) || cond_K_padd(i + 1 + 1,j + 1) || cond_K_padd(i + 1 + 1,j + 1 + 1));
        ST62 = cond_K_padd(i + 1 - 1,j + 1 - 1) && ...
             cond_K_padd(i + 1 + 1,j + 1 - 1) && ...
             (cond_K_padd(i + 1 - 1,j + 1 + 1) || cond_K_padd(i + 1,j + 1 + 1) || cond_K_padd(i + 1 + 1,j + 1 + 1));
        ST63 = cond_K_padd(i + 1 + 1,j + 1 - 1) && cond_K_padd(i + 1 + 1,j + 1 + 1) && ...
             (cond_K_padd(i + 1 - 1,j + 1 - 1) || cond_K_padd(i + 1 - 1,j + 1) || cond_K_padd(i + 1 - 1,j + 1 + 1));
        ST64 = cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1 + 1) && ...
             (cond_K_padd(i + 1 - 1,j + 1 - 1) || cond_K_padd(i + 1, j + 1 - 1) || cond_K_padd(i + 1 + 1,j + 1 - 1));
        % Diagonal Branch
        ST71 = cond_K_padd(i + 1 - 1,j + 1) && ~cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1 - 1) && ~cond_K_padd(i + 1 + 1,j + 1);
        ST72 = ~cond_K_padd(i + 1 - 1,j + 1 - 1) && cond_K_padd(i + 1 - 1,j + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1) && cond_K_padd(i + 1 + 1,j + 1 + 1);
        ST73 = ~cond_K_padd(i + 1 - 1,j + 1) && cond_K_padd(i + 1 - 1,j + 1 + 1) && ...
             cond_K_padd(i + 1, j + 1 - 1) && ~cond_K_padd(i + 1,j + 1 + 1) && ...
             ~cond_K_padd(i + 1 + 1,j + 1 - 1) && cond_K_padd(i + 1 + 1,j + 1);
        ST74 = cond_K_padd(i + 1 - 1,j + 1 - 1) && ~cond_K_padd(i + 1 - 1,j + 1) && ...
             ~cond_K_padd(i + 1, j + 1 - 1) && cond_K_padd(i + 1,j + 1 + 1) && ...
             cond_K_padd(i + 1 + 1,j + 1) && ~cond_K_padd(i + 1 + 1,j + 1 + 1);
        
        delete_if_1(i,j) = ~(ST11 || ST12 || ST13 || ST14 || ST21 || ST22 || ST23 || ST24 || ST31 || ST32 || ST33 || ST34 || ...
            ST41 || ST42 || ST51 || ST52 || ST53 || ST54 || ST61 || ST62 || ST63 || ST64 || ST71 || ST72 || ST73 || ST74);
    end
end

end